export const TABLE_ROWS = [
  {
    no: 1,
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-3.jpg",
    name: "John Michael",
    company: "Creative Tim",
    salesBy: "Jane Doe",
    hotelName: "Hotel California",
    city: "Los Angeles",
    checkIn: "2024-07-10",
    checkOut: "2024-07-12",
    roomNights: 2,
    roomNumbers: "101, 102",
    totalRoomNights: 4,
    roomNightRate: 150,
    hotelBilling: 600,
    commissionRate: 10,
    commissionOnIncome: 60,
    gst: "12%",
    totalBilling: 660,
    reservationType: "Online",
    valueType: "Standard",
    invoiceNumber: "INV-001",
  },
  {
    no: 2,
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-2.jpg",
    name: "Alexa Liras",
    company: "Google",
    salesBy: "John Smith",
    hotelName: "The Plaza",
    city: "New York",
    checkIn: "2024-07-11",
    checkOut: "2024-07-13",
    roomNights: 2,
    roomNumbers: "201, 202",
    totalRoomNights: 6,
    roomNightRate: 180,
    hotelBilling: 1080,
    commissionRate: 15,
    commissionOnIncome: 162,
    gst: "18%",
    totalBilling: 1242,
    reservationType: "Corporate",
    valueType: "Premium",
    invoiceNumber: "INV-002",
  },
  // Add more entries as needed
];


  export const TABLE_HEAD = [
    "Sr.No",
    "Guest Name",
    "Company",
    "Sales By",
    "Hotel Name",
    "City",
    "Check-In",
    "Check-Out",
    "Room Nights",
    "Room Numbers",
    "Total Room Nights",
    "Room Night Rate",
    "Hotel Billing",
    "Commission Rate",
    "Commission on Income",
    "GST",
    "Total Billing (3h)",
    "Reservation Type",
    "Value Type",
    "Invoice Number",
  ];
  


 export const tabsData = [
    {
      label: "Number of Rooms",
      value: "number",
      darkenColor: "#212b36",
      color: "#212b36",
    },
    {
      label: "Total Room Nights",
      value: "nights",
      darkenColor: "#22c55e",
      color: "#dbf6e5",
    },
    {
      label: "Commission on Income",
      value: "commissionOnIncome",
      darkenColor: "#ffab00",
      color: "#fff1d6",
    },
    {
      label: "Total Billing",
      value: "totalBilling",
      darkenColor: "#ff5630",
      color: "#ffe4de",
    },
    // {
    //   label: 'Draft',
    //   value: 'draft',
    //   darkenColor: '#212b36',
    //   color: '#edeff1',
    // },
  ];
  